### ISSUE TITLE
ValueError: Pipeline cannot infer suitable model classes from LiheYoung/depth-anything-small-hf

### ISSUE THREAD

**Issue by Pandapip1** [LiheYoung/Depth-Anything#103]
When attempting to use transformers, I get the following error:

```python
from transformers import pipeline
from PIL import Image

image = Image.open('./testimage.jpg')
pipe = pipeline(task="depth-estimation", model="LiheYoung/depth-anything-small-hf")
depth = pipe(image)["depth"]
```

```console
(.venv) gavin@gavin-ideapad-1:~/repos/ai-6dof$ python main.py 
2024-02-26 14:38:12.623114: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-26 14:38:12.661710: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-26 14:38:12.661768: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-26 14:38:12.663446: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-26 14:38:12.672494: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-26 14:38:12.672769: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-26 14:38:13.625810: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/gavin/repos/ai-6dof/main.py", line 5, in <module>
    pipe = pipeline(task="depth-estimation", model="LiheYoung/depth-anything-small-hf")
  File "/home/gavin/repos/ai-6dof/.venv/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 905, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/gavin/repos/ai-6dof/.venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 260, in infer_framework_load_model
    raise ValueError(f"Pipeline cannot infer suitable model classes from {model}")
ValueError: Pipeline cannot infer suitable model classes from LiheYoung/depth-anything-small-hf
```

**Comment by LiheYoung** [comment]
Hi, did you install the latest [``transformers``](https://github.com/huggingface/transformers)? Please update your ``transformers`` by:
```bash
pip3 install git+https://github.com/huggingface/transformers.git
```

**Comment by Pandapip1** [comment]
Pretty sure I had the latest transformers. I ended up getting around this issue by using the image_processor -> model split pipeline.

**Comment by LiheYoung** [comment]
I checked with ``transformers 4.38.2``. Your code above can be successfully executed. I am a little confused what the problem is. Do you still have this error?

**Comment by Pandapip1** [comment]
> Do you still have this error?

No, but I'm not using that code anymore. I'll close this since I found an easy workaround.

**Comment by JohannaDK** [comment]
Hello, could you please share how you fixed the issue? What is the new code, I have the same issue and cant fix it.

**Comment by Pandapip1** [comment]
I'm afraid I don't have that code anymore. Use the image_processor -> model split pipeline.

**Comment by 71walceli** [comment]
Still happens to me. 

Did given command...
> ```shell
> pip3 install git+https://github.com/huggingface/transformers.git
> ```

but still, throws given exception. Could you please explain how you managed to get it working?

This is what I get from REPL:

```py
Python 3.11.4 (main, Sep 14 2024, 19:18:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import pipeline
2024-09-24 20:43:27.126623: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-24 20:43:27.358171: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-24 20:43:27.579991: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-24 20:43:27.758034: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-24 20:43:27.807500: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-24 20:43:28.180905: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-24 20:43:30.085861: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> depth_pipeline = pipeline(task="depth-estimation", model="LiheYoung/depth-anything-small-hf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wceli/Projects/Clientes/Upwork/Keunhyuk Jang, J/Pipeline Code/upwork__keunhyuk_jang_J/lib/python3.11/site-packages/transformers/pipelines/__init__.py", line 896, in pipeline
    framework, model = infer_framework_load_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wceli/Projects/Clientes/Upwork/Keunhyuk Jang, J/Pipeline Code/upwork__keunhyuk_jang_J/lib/python3.11/site-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    raise ValueError(f"Pipeline cannot infer suitable model classes from {model}")
ValueError: Pipeline cannot infer suitable model classes from LiheYoung/depth-anything-small-hf
```
