### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by XinyaChen21** [LiheYoung/Depth-Anything#105]
when run 'depth_anything = DepthAnything.from_pretrained(pretrained_model_name_or_path='LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()', there is a error 'TypeError: __init__() missing 1 required positional argument: 'config''

**Comment by maxin0002** [comment]
I have the same problem, have you solved it yet? My GPU is RTX3090.

**Comment by sunpihai-up** [comment]
> > I also faces this problem. When I load the model using local weights, I run `depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()`. I got the following error message:
> > ```
> > xFormers not available
> > xFormers not available
> > Loading weights from local directory
> > Traceback (most recent call last):
> >   File "/home/sph/code/Depth-Anything-main/run.py", line 36, in <module>
> >     depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> >     return fn(*args, **kwargs)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> >     instance = cls._from_pretrained(
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 489, in _from_pretrained
> >     return cls._load_as_safetensor(model, model_file, map_location, strict)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 528, in _load_as_safetensor
> >     with safe_open(model_file, framework="pt", device=map_location) as f:  # type: ignore [attr-defined]
> > NameError: name 'safe_open' is not defined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I load the model from network, I run `depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()`. I got the following error message:
> > ```
> > Traceback (most recent call last):
> >   File "/home/sph/code/Depth-Anything-main/run.py", line 35, in <module>
> >     depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> >     return fn(*args, **kwargs)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> >     instance = cls._from_pretrained(
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 485, in _from_pretrained
> >     model = cls(**model_kwargs)
> > TypeError: __init__() missing 1 required positional argument: 'config'
> > ```
> 
> The first error seems to be a safetensors version issue, executed the pip install --upgrade safetensors command, but after resolving this there was another file cannot be found error. The second one has not been solved yet

Thank you for your reply. You are right. When I upgraded `safetensors` I encountered the error that the corresponding file could not be found.
After locating the error location, I found that the code seemed to expect the model weights to be given in the format of a safe tensor, but the weight file provided by [LiheYoung/depth_anything_vits14 · Hugging Face](https://huggingface.co/LiheYoung/depth_anything_vits14) is `pytorch_model.bin`.

I found that I was able to get DepthAnything to work using the following method.

Firstly, instantiate the `DepthAnything` class using the `config.json` file provided by [LiheYoung/depth_anything_vits14 · Hugging Face](https://huggingface.co/LiheYoung/depth_anything_vits14). Then download the corresponding `.pth` file from [LiheYoung/Depth-Anything at main (huggingface.co)](https://huggingface.co/spaces/LiheYoung/Depth-Anything/tree/main). Finally, use `load_state_dict` function to load the `.pth` file we downloaded.

I made the following modifications to `run.py`, I hope it will help you.

```python
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# Load model from pth
import json
dir_path = './checkpoints/depth_anything_{}14'.format(args.encoder)
cfg_path = os.path.join(dir_path, 'config.json')
pth_path = os.path.join(dir_path, 'depth_anything_{}14.pth'.format(args.encoder))

with open(cfg_path) as f:
    cfg = json.load(f)
weights = torch.load(pth_path)

depth_anything = DepthAnything(cfg).to(DEVICE).eval()
depth_anything.load_state_dict(weights)

total_params = sum(param.numel() for param in depth_anything.parameters())
print('Total parameters: {:.2f}M'.format(total_params / 1e6))
```

**Comment by LiheYoung** [comment]
Hi all, thank you for your valuable discussions. I carefully examined the previous instructions I provided. It will cause the errors you have raised. I am very sorry for the incorrect instructions.

Now, I have updated the [instructions](https://github.com/LiheYoung/Depth-Anything#no-network-connection-cannot-load-these-models) for loading the model ***without*** network connections. This version should be correct. Please also take care of the updated downloading links of the pre-trained models.

Besides, when loading the model ***with*** network connections by:
```python
depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_vitl14')
```
This indeed does not incur the ``TypeError: __init__() missing 1 required positional argument: 'config'``. This error is raised only when you load the model using the above code line but without any network connections.

If there are any further questions, please feel free to drop them here.

**Comment by LeoRainly** [comment]
> Hi all, thank you for your valuable discussions. I carefully examined the previous instructions I provided. It will cause the errors you have raised. I am very sorry for the incorrect instructions.
> 
> Now, I have updated the [instructions](https://github.com/LiheYoung/Depth-Anything#no-network-connection-cannot-load-these-models) for loading the model _**without**_ network connections. This version should be correct. Please also take care of the updated downloading links of the pre-trained models.
> 
> Besides, when loading the model _**with**_ network connections by:
> 
> ```python
> depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_vitl14')
> ```
> 
> This indeed does not incur the `TypeError: __init__() missing 1 required positional argument: 'config'`. This error is raised only when you load the model using the above code line but without network connections to huggingface.
> 
> If there are any further questions, please feel free to drop them here.

I modified and reran the codes, however, error still occurred. I reviewed the modifications made by [sunpihai-up](https://github.com/sunpihai-up), and I guess that the line "DepthAnything.from_pretrained(model_configs[encoder])" in instructions should be changed to "DepthAnything(model_configs[encoder])". Am i right?

**Comment by hongjr03** [comment]
My [pr](https://github.com/LiheYoung/Depth-Anything/pull/114) might have fix the issue loading local models.

**Comment by LiheYoung** [comment]
@LeoRainly Oh yes. You are right. Thank you for your reminder.

**Comment by frothmoon** [comment]
@LiheYoung Hello, I try to download the file from [link](https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth), but it still shows that I cannot access it.  

```
# wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth
--2024-03-07 01:43:23--  https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth
Resolving huggingface.co (huggingface.co)... 199.16.156.38, 2a03:2880:f12c:83:face:b00c:0:25de
Connecting to huggingface.co (huggingface.co)|199.16.156.38|:443... failed: Connection timed out.
Connecting to huggingface.co (huggingface.co)|2a03:2880:f12c:83:face:b00c:0:25de|:443... failed: Network is unreachable.
```

**Comment by sunpihai-up** [comment]
> @LiheYoung Hello, I try to download the file from [link](https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth), but it still shows that I cannot access it.
> 
> ```
> # wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth
> --2024-03-07 01:43:23--  https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth
> Resolving huggingface.co (huggingface.co)... 199.16.156.38, 2a03:2880:f12c:83:face:b00c:0:25de
> Connecting to huggingface.co (huggingface.co)|199.16.156.38|:443... failed: Connection timed out.
> Connecting to huggingface.co (huggingface.co)|2a03:2880:f12c:83:face:b00c:0:25de|:443... failed: Network is unreachable.
> ```

It seems that the download failed due to network reasons. If you access huggingface from mainland China, you may need a VPN.

**Comment by frothmoon** [comment]
> > @LiheYoung Hello, I try to download the file from [link](https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth), but it still shows that I cannot access it.
> > ```
> > # wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth
> > --2024-03-07 01:43:23--  https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth
> > Resolving huggingface.co (huggingface.co)... 199.16.156.38, 2a03:2880:f12c:83:face:b00c:0:25de
> > Connecting to huggingface.co (huggingface.co)|199.16.156.38|:443... failed: Connection timed out.
> > Connecting to huggingface.co (huggingface.co)|2a03:2880:f12c:83:face:b00c:0:25de|:443... failed: Network is unreachable.
> > ```
> 
> It seems that the download failed due to network reasons. If you access huggingface from mainland China, you may need a VPN.


@sunpihai-up Thank you for your reply. I tried to download the relevant files from hf-mirror.com.

**Comment by antimattergroup** [comment]
> 我也面临这个问题。 当我使用局部权重加载模型时，我运行`depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()`. 我收到以下错误消息：
> 
> ```
> xFormers not available
> xFormers not available
> Loading weights from local directory
> Traceback (most recent call last):
>   File "/home/sph/code/Depth-Anything-main/run.py", line 36, in <module>
>     depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()
>   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
>     instance = cls._from_pretrained(
>   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 489, in _from_pretrained
>     return cls._load_as_safetensor(model, model_file, map_location, strict)
>   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 528, in _load_as_safetensor
>     with safe_open(model_file, framework="pt", device=map_location) as f:  # type: ignore [attr-defined]
> NameError: name 'safe_open' is not defined
> ```
> 
> 当我从网络加载模型时，我运行`depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()`. 我收到以下错误消息：
> 
> ```
> Traceback (most recent call last):
>   File "/home/sph/code/Depth-Anything-main/run.py", line 35, in <module>
>     depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()
>   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
>     instance = cls._from_pretrained(
>   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 485, in _from_pretrained
>     model = cls(**model_kwargs)
> TypeError: __init__() missing 1 required positional argument: 'config'
> ```

So.. I have another question of this report.
Did you fixout 'xFormers not available' warning?
Idk why it crashed some time when running run_video.py via cmd.

**Comment by antimattergroup** [comment]
> > 我也面临这个问题。 当我使用局部权重加载模型时，我运行`depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()`. 我收到以下错误消息：
> > ```
> > xFormers not available
> > xFormers not available
> > Loading weights from local directory
> > Traceback (most recent call last):
> >   File "/home/sph/code/Depth-Anything-main/run.py", line 36, in <module>
> >     depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> >     return fn(*args, **kwargs)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> >     instance = cls._from_pretrained(
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 489, in _from_pretrained
> >     return cls._load_as_safetensor(model, model_file, map_location, strict)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 528, in _load_as_safetensor
> >     with safe_open(model_file, framework="pt", device=map_location) as f:  # type: ignore [attr-defined]
> > NameError: name 'safe_open' is not defined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当我从网络加载模型时，我运行`depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()`. 我收到以下错误消息：
> > ```
> > Traceback (most recent call last):
> >   File "/home/sph/code/Depth-Anything-main/run.py", line 35, in <module>
> >     depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> >     return fn(*args, **kwargs)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> >     instance = cls._from_pretrained(
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 485, in _from_pretrained
> >     model = cls(**model_kwargs)
> > TypeError: __init__() missing 1 required positional argument: 'config'
> > ```
> 
> So.. I have another question of this report. Did you fixout 'xFormers not available' warning? Idk why it crashed some time when running run_video.py via cmd.

I guess may be because of 'xFormers not available'?

**Comment by sunpihai-up** [comment]
> > I also faces this problem.
> > When I load the model using local weights, I run depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval().
> > I got the following error message:
> > ```
> > xFormers not available
> > xFormers not available
> > Loading weights from local directory
> > Traceback (most recent call last):
> >   File "/home/sph/code/Depth-Anything-main/run.py", line 36, in <module>
> >     depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> >     return fn(*args, **kwargs)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> >     instance = cls._from_pretrained(
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 489, in _from_pretrained
> >     return cls._load_as_safetensor(model, model_file, map_location, strict)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 528, in _load_as_safetensor
> >     with safe_open(model_file, framework="pt", device=map_location) as f:  # type: ignore [attr-defined]
> > NameError: name 'safe_open' is not defined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I load the model from network, I run depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval().
> > I got the following error message:
> > ```
> > Traceback (most recent call last):
> >   File "/home/sph/code/Depth-Anything-main/run.py", line 35, in <module>
> >     depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> >     return fn(*args, **kwargs)
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> >     instance = cls._from_pretrained(
> >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 485, in _from_pretrained
> >     model = cls(**model_kwargs)
> > TypeError: __init__() missing 1 required positional argument: 'config'
> > ```
> 
> @sunpihai-up So.. I have another question of this report. Did you fixout 'xFormers not available' warning? Idk why it crashed some time when running run_video.py via cmd. I guess may be because of 'xFormers not available'?

@antimattergroup I also don't know what the purpose of `xFormers` is. I simply installed it using `pip install xformers`, and then I no longer received the warning `xFormers not available`. Additionally, I haven't attempted to use `run_video.py`, so my experience may not necessarily be effective.

**Comment by antimattergroup** [comment]
> > > I also faces this problem.
> > > When I load the model using local weights, I run depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval().
> > > I got the following error message:
> > > ```
> > > xFormers not available
> > > xFormers not available
> > > Loading weights from local directory
> > > Traceback (most recent call last):
> > >   File "/home/sph/code/Depth-Anything-main/run.py", line 36, in <module>
> > >     depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_{}14'.format(args.encoder), local_files_only=True).to(DEVICE).eval()
> > >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> > >     return fn(*args, **kwargs)
> > >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> > >     instance = cls._from_pretrained(
> > >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 489, in _from_pretrained
> > >     return cls._load_as_safetensor(model, model_file, map_location, strict)
> > >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 528, in _load_as_safetensor
> > >     with safe_open(model_file, framework="pt", device=map_location) as f:  # type: ignore [attr-defined]
> > > NameError: name 'safe_open' is not defined
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > When I load the model from network, I run depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval().
> > > I got the following error message:
> > > ```
> > > Traceback (most recent call last):
> > >   File "/home/sph/code/Depth-Anything-main/run.py", line 35, in <module>
> > >     depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()
> > >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
> > >     return fn(*args, **kwargs)
> > >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 277, in from_pretrained
> > >     instance = cls._from_pretrained(
> > >   File "/home/sph/anaconda3/envs/anything/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 485, in _from_pretrained
> > >     model = cls(**model_kwargs)
> > > TypeError: __init__() missing 1 required positional argument: 'config'
> > > ```
> > 
> > 
> > @sunpihai-up So.. I have another question of this report. Did you fixout 'xFormers not available' warning? Idk why it crashed some time when running run_video.py via cmd. I guess may be because of 'xFormers not available'?
> 
> @antimattergroup I also don't know what the purpose of `xFormers` is. I simply installed it using `pip install xformers`, and then I no longer received the warning `xFormers not available`. Additionally, I haven't attempted to use `run_video.py`, so my experience may not necessarily be effective.

Could I know witch version of torch & xformers you installed?

**Comment by sunpihai-up** [comment]
@antimattergroup 
`pip list`
```text
Package                   Version
------------------------- ----------
aiofiles                  23.2.1
altair                    5.2.0
annotated-types           0.6.0
anyio                     4.3.0
attrs                     23.2.0
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.2.0
cycler                    0.12.1
exceptiongroup            1.2.0
fastapi                   0.110.0
ffmpy                     0.3.2
filelock                  3.13.1
fonttools                 4.49.0
fsspec                    2024.2.0
gradio                    4.14.0
gradio_client             0.8.0
gradio_imageslider        0.0.18
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.21.3
idna                      3.6
importlib_resources       6.1.2
Jinja2                    3.1.3
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.3
mdurl                     0.1.2
mpmath                    1.3.0
networkx                  3.2.1
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
opencv-python             4.9.0.80
orjson                    3.9.15
packaging                 23.2
pandas                    2.2.1
pillow                    10.2.0
pip                       23.3.1
pydantic                  2.6.3
pydantic_core             2.16.3
pydub                     0.25.1
Pygments                  2.17.2
pyparsing                 3.1.1
python-dateutil           2.8.2
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.33.0
requests                  2.31.0
rich                      13.7.1
rpds-py                   0.18.0
safetensors               0.4.2
semantic-version          2.10.0
setuptools                68.2.2
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
starlette                 0.36.3
sympy                     1.12
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.2.0
torchvision               0.17.0
tqdm                      4.66.2
triton                    2.2.0
typer                     0.9.0
typing_extensions         4.10.0
tzdata                    2024.1
urllib3                   2.2.1
uvicorn                   0.27.1
websockets                11.0.3
wheel                     0.41.2
xformers                  0.0.24
zipp                      3.17.0
```

**Comment by antimattergroup** [comment]
@sunpihai-up now I know it is brcause triton can't run on Win sys. thx
I signed up for a remote server.
