### ISSUE TITLE
TypeError: "__init__()"miss 1 requirement positional argument:"config" 

### ISSUE THREAD

**Issue by guoyanzhongwgfufg** [LiheYoung/Depth-Anything#211]
I just run CLI : python3 run.py --encoder vist --img-path 12.png --outdir dep_predict  , it made the following  error.
I have placed 12.png in the current directory. 

Traceback (most recent call last):
  File "run.py", line 34, in <module>
    depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/hub_mixin.py", line 558, in from_pretrained
    instance = cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/hub_mixin.py", line 778, in _from_pretrained
    model = cls(**model_kwargs)
TypeError: __init__() missing 1 required positional argument: 'config'

How did it run and where is  i go wrong? please guide me ,thanks.

**Comment by LiheYoung** [comment]
You may follow [this](https://github.com/LiheYoung/Depth-Anything#no-network-connection-cannot-load-these-models) to load our model.

**Comment by guoyanzhongwgfufg** [comment]
您好，邮件我已收到，我会尽快处理，谢谢。
