### ISSUE TITLE
evaluate.py   issue

### ISSUE THREAD

**Issue by Thundermean-sky** [LiheYoung/Depth-Anything#237]
Traceback (most recent call last):
  File "D:\master_doc\experiment\Depth-Anything\metric_depth\evaluate.py", line 159, in <module>
    eval_model(args.model, pretrained_resource=args.pretrained_resource,
  File "D:\master_doc\experiment\Depth-Anything\metric_depth\evaluate.py", line 131, in eval_model
    metrics = main(config)
  File "D:\master_doc\experiment\Depth-Anything\metric_depth\evaluate.py", line 115, in main
    metrics = evaluate(model, test_loader, config)
  File "C:\Users\Mean\.conda\envs\yolo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\master_doc\experiment\Depth-Anything\metric_depth\evaluate.py", line 108, in evaluate
    metrics = {k: r(v) for k, v in metrics.get_value().items()}
AttributeError: 'NoneType' object has no attribute 'items'

When I try to evaluate vitl, it shows an error. When I print the metrics, it print {'_dic': None}. How can I fix this?

code position: evaluate.py---108

**Comment by Skapis9999** [comment]
@Thundermean-sky have you solved the issue?
